# Generated by Django 5.0.4 on 2024-04-13 07:05

from django.db import migrations, models
from django.conf import settings
from django.core.files import storage


# Determine the storage class for the gallery
try:
    GalleryStorageClass = storage.get_storage_class(settings.GALLERY_STORAGE)
except AttributeError:
    GalleryStorageClass = None


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='exif_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(storage=GalleryStorageClass, upload_to='images'),
        ),
    ]
