# Generated by Django 5.0.4 on 2024-04-22 20:24

import gallery.models
import main.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_defaults_for_image_date_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='album_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(storage=main.storage_backends.S3PrivateMediaStorage(), upload_to=gallery.models.Image.upload_dir),
        ),
    ]
