# Generated by Django 5.0.4 on 2024-04-22 20:24

import gallery.models
from django.db import migrations, models
from django.conf import settings
from django.core.files import storage


# Determine the storage class for the gallery
try:
    GalleryStorageClass = storage.get_storage_class(settings.GALLERY_STORAGE)
except AttributeError:
    GalleryStorageClass = None


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_defaults_for_image_date_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='album_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(storage=GalleryStorageClass,
                                    upload_to=gallery.models.Image.upload_dir),
        ),
    ]
